# Generated by Django 6.0.5 on 2026-06-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchatDevises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('Numero', models.CharField(max_length=50)),
                ('devise', models.CharField(max_length=50)),
                ('cours', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
