# Generated by Django 6.0.5 on 2026-07-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_app', '0002_achatdevises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achatdevises',
            old_name='Numero',
            new_name='numero',
        ),
        migrations.AddField(
            model_name='achatdevises',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
